AGM.Payments/Controllers/EmployeeController.cs
using AGM.Payments.Business;
using AGM.Payments.Fliters;
using AGM.Payments.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGM.Payments.Controllers
{
    [CustomError(View = "Error")]
    public class EmployeeController : Controller
    {
        // GET: Employee
        [EmployeeAuth]
        public ActionResult Index()
        {
            ResmanSession resman = Session["Resman"] as ResmanSession;
            EmployeeProperties empProp = new EmployeeProperties();
            Session["UserName"] = resman.EmployeeUser.Name;
            empProp.Properties = resman.EmployeeUser.Properties;
            return View(empProp);
        }

        [EmployeeAuth]
        [HttpGet()]
        public JsonResult List(string propertyID)
        {
            ResidentListViewModel model = new ResidentListViewModel();
            ResmanSession resman = Session["Resman"] as ResmanSession;
            //model.PropertyName = resman.EmployeeUser.Properties.Where(x => x.Value == propertyID).FirstOrDefault().DisplayText;
            model.Accounts = AccountHandler.GetAccounts(propertyID);

            //model.Accounts = accounts.Where(x => x.Status == "Current").ToList();     
            var jsonResult = new
            {
                data = model.Accounts.ToList()
            };       
            return Json(jsonResult, JsonRequestBehavior.AllowGet);
        }
    }
}

AGM.Payments/Controllers/TransactionsController.cs
using AGM.Payments.Fliters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGM.Payments.Controllers
{
    [CustomError(View = "Error")]
    public class TransactionsController : Controller
    {
        // GET: Transactions
        [AdminAuth]
        public ActionResult Index()
        {
            return View();
        }
    }
}

AGM.Payments/Views/Shared/Employee.cshtml
@using AGM.Payments.Utility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - My Resman Payments</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Forword.js"></script>

</head>

<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <img src="~/Images/Live-Active.png" alt="Live Active" title="Live Active">
            </div>
        </div>
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Resman Payments", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index", "Employee")">Payment</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @{
                        string userName = Session["UserName"] as string;
                        string profileID = (Session["Resman"] as AGM.Payments.Model.ResmanSession).EmployeeUser.EmployeeID.ToString();
                    }

                    <li>
                        <a href="#"  class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user control-label"> @userName</span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index","Profile",new { profileID= profileID, profileType= "Employee"})">Profile</a></li>
                            <li><a href="#">Change Password</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("SignOut","Home")"><span class="glyphicon glyphicon-log-out"></span> SignOut</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()

    </div>
    <br />
    <div>
        <p class="panel-footer navbar-fixed-bottom text-center">&copy; @DateTime.Now.Year - My Resman Payments</p>
    </div>
</body>
</html>

AGM.Payments/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - My Resman Payments</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Forword.js"></script>

</head>
<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <img src="~/Images/Live-Active.png" alt="Live Active" title="Live Active">
            </div>
        </div>
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Resman Payments", "Index", "Resman", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Resman")">Home</a></li>
                        <li><a href="@Url.Action("List", "AuthorizeConfiguration")">Authorize.Net</a></li>
                        <li><a href="@Url.Action("PropertyToPayment", "Resman")">Property Payment Map</a></li>
                        <li><a href="@Url.Action("EmployeeConfiguration", "Resman")">Employee Configuration</a></li>
                        <li><a href="@Url.Action("Index", "Transactions")">Transactions</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @{
                            string userName = Session["UserName"] as string;
                        }
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> @userName</a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Profile", "Resman")">Profile</a></li>
                                <li><a href="#">Change Password</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("SignOut", "Home")"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <br />
    </div>
    <div>
        <p class="panel-footer navbar-fixed-bottom text-center">&copy; @DateTime.Now.Year - My Resman Payments</p>
    </div>
    <script>

    </script>
</body>
</html>

AGM.Payments/Views/Shared/_Common.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - My Resman Payments</title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Forword.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <img src="~/Images/Live-Active.png" alt="Live Active" title="Live Active">
            </div>
        </div>
    </div>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Resman Payments", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <br />
        @RenderBody()
        <br />
    </div>
    <div>
        <p class="panel-footer navbar-fixed-bottom text-center">&copy; @DateTime.Now.Year - My Resman Payments</p>
    </div>
</body>
</html>